package com.hwxy.code.leetcode.interview.in17.i11;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class In17I11Test {

    @Test
    public void findClosest() {
        In17I11 in17I11 = new In17I11();
        // assertEquals(1, in17I11.findClosest(new String[] {"I", "am", "a", "student", "from", "a",
        // "university", "in", "a", "city"}, "a", "student"));
        // assertEquals(1, in17I11.findClosest(new String[] {"I", "am", "a", "student", "from", "a",
        // "university", "in", "a", "city"}, "student", "a"));
        // assertEquals(1, in17I11.findClosest(new String[] {"a", "student"}, "student", "a"));
        // assertEquals(1, in17I11.findClosest(new String[] {"a", "student"}, "a", "student"));
        assertEquals(32, in17I11.findClosest(new String[] {"foa", "lnm", "g", "g", "ke", "zrf",
                "ri", "nvd", "ukz", "zb", "b", "gal", "f", "eop", "di", "kgk", "hyo", "ffb", "tun",
                "lon", "doi", "z", "udg", "t", "t", "mgy", "o", "a", "mgq", "k", "u", "lug", "n",
                "sff", "gq", "zfy", "k", "kt", "nbm", "azu", "umg", "aea", "v", "cy", "s", "u", "p",
                "uq", "uox", "kio", "w", "p", "uhh", "yuw", "cgi", "fr", "n", "v", "pz", "lj", "n",
                "cx", "hhc", "r", "cdn", "sp", "pub", "ak", "nw", "jre", "w", "yh", "se", "e", "x",
                "i", "ga", "to", "rg", "t", "wbe", "t", "zdc", "l", "iy", "dt", "h", "lpp", "o",
                "eie", "kxe", "zm", "pm", "m", "yn", "mh", "dhe", "cmm", "yz", "mbm", "p", "cbu",
                "uf", "rz", "x", "fg", "ty", "te", "wd", "cjy", "p", "mr", "y", "kn", "fen", "ok",
                "dyj", "xmr", "rjy", "gv", "g", "tqw", "ybf", "xcf", "y", "nuf", "aoq", "r", "nko",
                "av", "u", "h", "at", "dq", "vg", "oc", "ly", "ao", "j", "m", "ab", "dvj", "to",
                "mc", "q", "x", "zma", "jj", "iz", "fu", "bna", "yrv", "ux", "vyt", "xif", "s",
                "ws", "dzb", "wta", "vz", "ujy", "a", "tzd", "t", "dw", "b", "v", "r", "flm", "rzc",
                "o", "ku", "l", "o", "kx", "gg", "u", "qou", "w", "fip", "af", "i", "k", "x", "lbe",
                "rpy", "dh", "cz", "kw", "yph", "tb", "kxi", "mz", "msw", "v", "hol", "s", "rf",
                "fqq", "z", "i", "nr", "ue", "rl", "tg", "xzr", "fa", "mva", "ay", "aw", "gau",
                "pce", "g", "d", "o", "t", "zgq", "xf", "diu", "r", "jid", "bvg", "l", "z", "lsl",
                "pep", "g", "zkk", "h", "n", "xl", "ktk", "bbe", "hb", "cd", "ln", "o", "zlt",
                "kms", "sf", "cf", "a", "e", "pg", "ni", "sb", "k", "js", "l", "k", "n", "rjg",
                "cdo", "ri", "lx", "m", "qgm", "yen", "c", "k", "la", "cyk", "oqh", "un", "axv",
                "j", "vu", "ikc", "vb", "au", "fy", "ert", "jol", "qg", "u", "s", "g", "ldy", "ng",
                "k", "elk", "xlw", "rtu", "wh", "s", "cfo", "bi", "bfa", "qub", "tjr", "ca", "go",
                "lt", "dkg", "h", "rsv", "g", "uv", "dl", "is", "oa", "f", "o", "zfj", "br", "yrc",
                "i", "iej", "sqa", "syd", "lg", "omm", "bp", "o", "qwl", "b", "coe", "qd", "t",
                "wap", "o", "pab", "ji", "jl", "o", "ih", "dev", "s", "x", "jb", "w", "a", "ij",
                "uop", "nzk", "r", "o", "e", "asq", "x", "a", "ygf", "ios", "wvn", "jp", "a", "c",
                "e", "isu", "fj", "q", "kgx", "i", "uw", "spa", "jm", "bco", "e", "btr", "wr",
                "hrn", "lpx", "pfe", "eou", "g", "coz", "m", "m", "x", "s", "g", "o", "qn", "f",
                "g", "ic", "e", "diy", "k", "vc", "z", "g", "d", "iqd", "os", "r", "llp", "rlo",
                "qv", "vbf", "md", "gu", "bmj", "pl", "u", "vk", "yc", "tyf", "r", "h", "ym", "xn",
                "ef", "e", "kp", "hap", "d", "l", "w", "as", "po", "dch", "k", "ukz", "qc", "l",
                "e", "sps", "df", "eqc", "ps", "jr", "fq", "ew", "kd", "b", "sn", "j", "ccx", "v",
                "juu", "uhf", "dr", "o", "quq", "i", "ldi", "li", "d", "ka", "a", "tc", "yrg",
                "xpv", "ug", "lri", "yk", "cr", "r", "awr", "bpw", "bcs", "p", "c", "fdz", "gp",
                "kn", "b", "ou", "ljo", "swq", "xgf", "cbt", "iax", "k", "md", "lz", "s", "q",
                "uar", "fdg", "he", "mgw", "u", "a", "mn", "i", "y", "vsh", "yis", "gj", "z", "kuo",
                "vq", "v", "ngs", "f", "el", "z", "k", "g", "d", "e", "jbj", "kyl", "z", "uw",
                "ttl", "og", "lxr", "i", "mvn", "jn", "kdq", "hsw", "ntu", "q", "m", "vra", "z",
                "wsa", "lwe", "e", "a", "vxi", "oyj", "pm", "vm", "h", "vfd", "yf", "vs", "x",
                "iim", "p", "ltj", "z", "a", "owc", "ek", "gzl", "wrw", "tuq", "ff", "e", "f", "r",
                "s", "n", "bz", "d", "f", "yy", "hdl", "lss", "wzt", "ow", "r", "xag", "fz", "r",
                "zhw", "y", "p", "mxr", "xf", "u", "ord", "d", "ttj", "eg", "m", "lg", "pj", "u",
                "s", "ck", "h", "x", "ia", "i", "qmw", "if", "x", "vr", "jt", "qv", "rgz", "o",
                "qgu", "r", "vvy", "et", "cn", "hkx", "xqc", "pwh", "ma", "za", "rug", "t", "yws",
                "yft", "o", "s", "dym", "jkk", "e", "rpi", "jk", "ztq", "cr", "wk", "fc", "k", "nb",
                "zn", "soy", "n", "cz", "eox", "qm", "d", "foj", "vgq", "z", "h", "yue", "n", "hly",
                "hyr", "bqw", "sub", "b", "xuq", "hs", "ism", "ld", "f", "m", "cu", "dl", "kn",
                "go", "ooo", "mq", "spp", "tjy", "mcs", "k", "i", "a", "r", "gn", "ue", "ix", "gr",
                "j", "vdr", "x", "tzw", "jsx", "j", "j", "j", "ps", "no", "gkc", "e", "iyx", "a",
                "nu", "hf", "iz", "ve", "b", "czq", "w", "dgy", "g", "jck", "mfq", "o", "kje",
                "fif", "gw", "npp", "x", "o", "yms", "efu", "pa", "qhl", "w", "ne", "jxp", "gl",
                "wmf", "cmk", "iel", "on", "f", "tmw", "m", "r", "xgw", "a", "p", "f", "qis", "wdg",
                "os", "gs", "e", "ktg", "s", "zl", "v", "m", "x", "wq", "x", "gz", "f", "g", "ve",
                "cb", "p", "esd", "vj", "vd", "j", "j", "fz", "jgj", "t", "rbt", "oxk", "by", "g",
                "w", "el", "f", "pvn", "pd", "h", "e", "rx", "lvm", "mpo", "u", "bqm", "sbv", "rv",
                "g", "z", "psn", "mxn", "uj", "bnl", "nc", "bj", "l", "vyk", "ccv", "hvq", "zas",
                "bj", "tva", "db", "pw", "i", "bat", "ds", "xsm", "hia", "qm", "hra", "u", "xw",
                "iv", "d", "m", "ym", "h", "u", "i", "qro", "m", "fz", "dby", "gv", "tb", "u",
                "fbg", "h", "vdq", "pip", "qtf", "h", "orl", "s", "pj", "pb", "y", "r", "ztx", "e",
                "m", "ae", "fnc", "mvu", "o", "wq", "cls", "qt", "i", "gk", "e", "ob", "r", "ui",
                "rw", "dtn", "wzq", "jhh", "bxv", "ao", "nu", "wpq", "opg", "w", "et", "ve", "wa",
                "p", "ula", "sv", "p", "op", "ztm", "kra", "l", "jmy", "pve", "q", "bpb", "im", "h",
                "oa", "q", "n", "xm", "jtp", "fag", "nto", "r", "o", "r", "p", "ej", "o", "nr",
                "awd", "ce", "yf", "v", "cbn", "gxb", "fhi", "zk", "oc", "yzj", "wja", "tx", "i",
                "z", "aet", "gdc", "olb", "r", "gti", "ccp", "xzb", "eod", "ot", "g", "qj", "te",
                "c", "n", "zgx", "ol", "a", "w", "zu", "x", "g", "uan", "sak", "y", "zdi", "o",
                "we", "nl", "hgq", "yum", "d", "f", "k", "afu", "evm", "my", "dz", "av", "x", "e",
                "bj", "tir", "a", "kyn", "sa", "sii", "u", "adz", "hz", "cao", "m", "sjp", "fd",
                "ci", "t", "jvj", "ze", "h", "q", "l", "aau", "pfg", "fs", "rjb", "et", "qnq",
                "zuk", "aiw", "ehy", "wf", "px", "xyp", "g", "nal", "tyy", "ub", "k", "ic", "bb",
                "zer", "bp", "y", "i", "z", "wxa", "pfp", "qo", "unh", "twk", "tet", "fn", "rbz",
                "qi", "eh", "j", "pte", "dkh", "n", "gvf", "b", "md", "ht", "j", "lkj", "jpy", "ki",
                "a", "zx", "ell", "ew", "ccn", "ul", "bvj", "oxg", "t", "a", "zg", "ll", "zia",
                "uo", "rg", "dq", "u", "brc", "rad", "sfq", "mus", "k", "ada", "l", "o", "n", "ojj",
                "x", "oz", "vi", "fg", "yab", "qje", "mw", "br", "hl", "z", "of", "g", "cep", "zbe",
                "dpp", "b", "yf", "jc", "ro", "ou", "bg", "en", "qpi", "in", "lid", "n", "w", "yc",
                "o", "rg", "jj", "qv", "j", "p", "b", "c", "gp", "s", "vq", "g", "kf", "s", "epr",
                "cg", "lce", "y", "sox", "g", "ks", "vdb", "z", "i", "kf", "nk", "t", "c", "fxn",
                "qsi", "xav", "gz", "u", "ukq", "yyy", "y", "u", "j", "qm", "zam", "sdg", "zv",
                "zr", "z", "a", "ry", "ts", "n", "ul", "djo", "br", "rdr", "bf", "mlm", "q", "ax",
                "g", "xri", "pes", "bzh", "df", "oq", "fp", "rbv", "zo", "sz", "pma", "nva", "dtu",
                "gt", "h", "hww", "nc", "ks", "flv", "jwe", "j", "sif", "ht", "j", "dcm", "rn",
                "kg", "hkb", "ik", "mlr", "gaf", "nkk", "o", "xq", "xxs", "o", "sz", "sny", "u",
                "ao", "y", "nkf", "y", "ned", "hf", "okh", "ud", "r", "bwg", "a", "b", "wl", "ex",
                "a", "zam", "oxi", "ylw", "ul", "dat", "vqp", "bei", "c", "jx", "m", "b", "qas",
                "e", "v", "xtc", "jf", "g", "dc", "a", "r", "fs", "h", "n", "s", "i", "b", "nqt",
                "ui", "ijm", "xny", "pcc", "v", "vcq", "xs", "c", "q", "ai", "hm", "u", "dz", "a",
                "yo", "xvt", "kni", "u", "d", "dmg", "kug", "v", "k", "nbk", "ltt", "etk", "ejd",
                "k", "s", "ds", "y", "z", "jsv", "xo", "zub", "e", "ac", "f", "ph", "fq", "hrr",
                "hfo", "lca", "d", "qk", "xz", "tl", "ms", "eqw", "vbr", "z", "mg", "uy", "x", "tg",
                "mn", "if", "d", "g", "yzw", "mc", "ksi", "zx", "th", "ye", "jm", "me", "kgp", "gf",
                "y", "aog", "cqs", "l", "h", "kfq", "r", "u", "b", "n", "kxf", "swj", "lkz", "pfi",
                "r", "w", "s", "vcb", "vu", "cf", "mv", "m", "gt", "i", "s", "u", "q", "kq", "sz",
                "et", "zph", "dtm", "kgb", "ww", "sz", "sm", "cv", "hqs", "oea", "i", "els", "a",
                "nwk", "klb", "nn", "c", "snr", "z", "pd", "sj", "bsn", "yj", "irp", "pyt", "cqv",
                "ogm", "qz", "z", "m", "wqx", "l", "pqm", "use", "gn", "z", "vln", "nxq", "xu", "h",
                "lh", "c", "g", "za", "epn", "j", "m", "wv", "v", "i", "vz", "dpe", "w", "zs",
                "gch", "p", "lz", "clx", "lcc", "kki", "pv", "xj", "nt", "yi", "iqu", "fa", "stg",
                "nei", "al", "dnx", "x", "nih", "fue", "ok", "y", "uat", "us", "ej", "tyg", "p",
                "pwl", "gwf", "djl", "hyg", "w", "val", "qnw", "crv", "d", "pgt", "n", "imt", "r",
                "g", "c", "af", "m", "gg", "j", "a", "ko", "jmw", "y", "blj", "eu", "swy", "yqc",
                "t", "h", "zfk", "unp", "p", "end", "i", "lh", "z", "qni", "te", "m", "h", "xsw",
                "zxw", "pu", "dz", "eq", "q", "zjb", "j", "pt", "z", "nj", "zlg", "f", "eny", "pq",
                "jxq", "tqm", "o", "c", "x", "n", "ybg", "o", "ec", "xvf", "wbx", "cx", "f", "z",
                "cr", "aq", "edl", "oww", "heo", "sn", "n", "rh", "by", "hty", "ypr", "lb", "jk",
                "wbd", "ds", "h", "x", "yo", "p", "rcp", "d", "wdj", "ltk", "wuv", "fsg", "ec",
                "xvm", "za", "i", "fax", "wox", "k", "mcy", "x", "m", "uzx", "p", "v", "hsw", "tf",
                "oms", "ou", "tnw", "r", "yrd", "to", "ip", "jld", "e", "w", "qh", "xb", "wj", "u",
                "rh", "z", "nd", "z", "cd", "ze", "ntp", "q", "ot", "rpm", "vqw", "wbt", "hfu", "s",
                "k", "s", "zgd", "l", "xh", "uqc", "o", "n", "mdi", "zcc", "ec", "oo", "ky", "kjx",
                "cg", "o", "naq", "m", "w", "xzu", "y", "a", "bwz", "hj", "gmd", "eiz", "wdh",
                "qmn", "tj", "r", "pk", "duf", "q", "t", "zd", "m", "tyo", "et", "wm", "vv", "i",
                "ou", "gwx", "yrf", "lgf", "ki", "m", "jyd", "pk", "h", "k", "sr", "yjq", "evu",
                "vr", "xa", "cxo", "o", "vqs", "pc", "ijy", "v", "gl", "xf", "be", "do", "pf", "qo",
                "pw", "oq", "yyf", "r", "n", "ip", "rjz", "x", "gq", "h", "wbv", "wva", "ygs", "f",
                "ce", "f", "p", "tut", "wka", "dq", "c", "q", "xs", "icv", "d", "mzv", "udx", "qvv",
                "t", "m", "dh", "qa", "k", "e", "xtj", "sx", "dza", "x", "t", "js", "wyi", "u", "m",
                "d", "zpx", "for", "q", "k", "xx", "z", "n", "n", "o", "jw", "gh", "n", "vz", "q",
                "l", "lfm", "abb", "r", "nmz", "s", "kdh", "a", "f", "dq", "bsy", "tw", "m", "s",
                "eta", "ir", "se", "urh", "eq", "rmn", "t", "dk", "qmc", "esw", "k", "nep", "qf",
                "gw", "npp", "ox", "z", "vn", "ia", "deq", "tki", "w", "l", "zd", "y", "k", "kd",
                "kf", "mp", "txu", "ynj", "xs", "an", "t", "h", "h", "pu", "v", "aq", "hih", "hpr",
                "mjw", "y", "w", "zfe", "gye", "aam", "hs", "x", "ihy", "euy", "yh", "whp", "yvf",
                "whu", "b", "qc", "pl", "bt", "cl", "zrk", "s", "ad", "bsv", "kvl", "ulz", "s",
                "qmp", "t", "cq", "erw", "y", "y", "i", "agj", "f", "ev", "a", "wm", "zm", "c",
                "kp", "j", "sjm", "aa", "nn", "pzn", "io", "hc", "yi", "g", "y", "u", "o", "lkh",
                "t", "zku", "ih", "xi", "nl", "fod", "g", "sld", "ra", "ir", "ndb", "q", "z", "zon",
                "w", "u", "oak", "jiq", "t", "s", "jib", "hf", "gti", "xq", "zmc", "a", "vnd", "ic",
                "eb", "p", "fvm", "o", "fc", "f", "gk", "dol", "voi", "ghi", "n", "nlw", "fw", "y",
                "ftj", "bc", "cn", "ox", "jzf", "ska", "bq", "g", "ehm", "uko", "suu", "s", "wr",
                "eq", "vbi", "ok", "kfw", "w", "lyx", "y", "it", "z", "u", "klt", "ml", "hjg", "fc",
                "nk", "xn", "jz", "dcu", "okk", "k", "t", "h", "z", "fuz", "kk", "o", "n", "f",
                "bc", "b", "ar", "d", "j", "p", "c", "wvl", "ry", "du", "vux", "u", "n", "am",
                "eqy", "yg", "pg", "gs", "wv", "qhh", "st", "cgp", "vnw", "vr", "vd", "jyv", "c",
                "mgh", "b", "vob", "t", "e", "gpx", "ha", "cqo", "vrl", "f", "q", "lce", "j", "o",
                "zru", "ys", "lrv", "wqe", "m", "kwv", "uy", "c", "y", "yq", "u", "n", "ew", "ph",
                "u", "ws", "yim", "o", "pi", "x", "jct", "l", "qe", "tn", "zqw", "sx", "tz", "x",
                "my", "pt", "au", "niu", "obx", "yi", "vn", "lqa", "nu", "lbt", "xtr", "xn", "l",
                "wr", "aou", "zdy", "do", "hd", "bk", "y", "aq", "o", "vh", "nwa", "d", "qt", "ibq",
                "nkg", "ka", "zt", "uxp", "u", "whp", "aod", "it", "rm", "kmb", "ft", "mbs", "dbs",
                "uj", "a", "msu", "g", "jiq", "hg", "m", "lb", "ds", "ypn", "tbe", "jyq", "mey",
                "vjw", "q", "afn", "bun", "aug", "mrd", "k", "fp", "bwv", "e", "x", "fke", "a",
                "vp", "nq", "nci", "xfn", "j", "lm", "ggx", "ni", "ol", "eej", "uz", "y", "qj",
                "fj", "lzy", "tes", "h", "qq", "p", "ne", "ycp", "vym", "pqk", "tq", "b", "l", "he",
                "fv", "p", "vz", "r", "l", "wos", "suk", "vy", "sd", "n", "l", "ho", "j", "ya",
                "ctn", "biq", "nu", "cp", "xh", "yav", "hd", "x", "b", "ef", "uic", "i", "rj", "qn",
                "ukj", "i", "gy", "zo", "oim", "vhp", "lmh", "l", "q", "gsn", "dxp", "qvl", "pln",
                "w", "za", "pz", "g", "t", "t", "gi", "qsu", "yn", "ilp", "mv", "dw", "v", "c", "k",
                "xpv", "xww", "ir", "nk", "vlg", "kpr", "lg", "zy", "zs", "e", "uls", "i", "hbw",
                "byh", "am", "ie", "e", "uh", "ry", "wd", "e", "f", "v", "wl", "nc", "i", "o", "y",
                "y", "f", "a", "mpl", "b", "gw", "sj", "fxa", "kqd", "ju", "iu", "zo", "hpx", "p",
                "gqr", "x", "mk", "ilb", "a", "fup", "dx", "lim", "c", "y", "njd", "sxg", "ua",
                "ih", "erp", "khn", "c", "vmq", "txc", "g", "cit", "mf", "pdl", "y", "s", "pxt",
                "ry", "t", "zln", "cq", "vu", "p", "v", "fo", "m", "l", "e", "ua", "ybu", "rsv",
                "r", "va", "mk", "vp", "z", "mj", "qb", "iv", "cxf", "vwy", "q", "gv", "ro", "f",
                "nnj", "cg", "g", "uqs", "ek", "vt", "dwa", "idc", "vx", "bja", "tb", "xg", "d",
                "gtz", "nck", "foa", "zlv", "r", "fg", "ipy", "qj", "oif", "ul", "t", "xlb", "ahl",
                "d", "a", "bz", "gb", "rd", "ob", "c", "mk", "xn", "t", "uw", "cwg", "awr", "w",
                "d", "q", "xj", "mmq", "t", "i", "tn", "k", "kc", "l", "kr", "ss", "cwc", "nq", "c",
                "t", "ced", "k", "qsz", "tcw", "z", "jn", "xgf", "u", "xe", "z", "zs", "cz", "qc",
                "yd", "a", "qn", "tkl", "kbk", "e", "b", "caz", "qya", "vxo", "ifv", "c", "wbo",
                "c", "m", "ib", "g", "lq", "rk", "cf", "gku", "i", "xo", "dx", "fi", "hlg", "z",
                "yzl", "t", "ve", "pm", "ymb", "ad", "to", "fbr", "i", "g", "yeq", "e", "k", "qff",
                "msy", "mq", "rwj", "sz", "bv", "gv", "xdr", "rb", "lx", "qsq", "mte", "vl", "nvs",
                "hzt", "s", "u", "rbg", "en", "s", "k", "ifb", "nw", "wy", "d", "brj", "vmf", "mxn",
                "v", "hg", "htu", "h", "s", "v", "eo", "rzc", "yaf", "w", "c", "zkc", "n", "dbv",
                "izs", "xkq", "khn", "fgy", "ho", "w", "v", "gnm", "r", "n", "mei", "jl", "peb",
                "wtg", "bv", "u", "noh", "ldg", "pst", "ja", "mt", "ay", "u", "yb", "cgt", "riu",
                "lvf", "q", "m", "v", "va", "n", "dt", "xag", "dqe", "a", "s", "kda", "md", "etj",
                "zp", "hk", "aof", "y", "ynx", "zh", "wjg", "kn", "md", "sns", "yxa", "c", "hon",
                "bo", "ywk", "ba", "ag", "yy", "dg", "trr", "y", "tp", "eiu", "j", "h", "bj", "ng",
                "s", "ic", "rp", "ev", "jb", "onb", "dbo", "tp", "x", "rs", "p", "wcg", "v", "q",
                "gjh", "yk", "ia", "yst", "cz", "alu", "nfj", "nss", "v", "ear", "vex", "swz", "cd",
                "niv", "mj", "z", "yl", "ll", "q", "i", "y", "m", "ru", "c", "vny", "db", "yk", "r",
                "dsm", "vi", "fg", "p", "vv", "xvx", "wl", "ga", "o", "z", "dt", "fl", "xi", "koe",
                "s", "qqj", "sqj", "br", "lnq", "q", "dj", "zm", "k", "yh", "o", "dxd", "b", "ap",
                "xw", "yuf", "p", "sae", "in", "ond", "i", "jzq", "hf", "vte", "xm", "a", "aqr",
                "kpc", "bff", "qgi", "xf", "nv", "m", "ii", "e", "kjo", "afp", "j", "s", "kbi", "d",
                "mp", "dx", "kbf", "s", "byr", "avo", "xpa", "ct", "lz", "ob", "gi", "lrr", "rsm",
                "xzf", "xts", "t", "gzi", "ihw", "xk", "ix", "r", "mey", "uk", "dcw", "d", "cu",
                "yx", "f", "nxx", "kn", "vv", "ocy", "nm", "ekh", "yf", "v", "qbd", "qor", "ch",
                "d", "ki", "w", "x", "nhg", "bp", "x", "c", "vv", "raa", "bd", "ir", "ohs", "lz",
                "vf", "fv", "l", "ffx", "urm", "ey", "x", "l", "ksj", "hr", "y", "f", "m", "qfv",
                "z", "r", "wvz", "b", "i", "fb", "tah", "wme", "nsw", "x", "yu", "wyk", "uoo", "q",
                "x", "psv", "pe", "b", "oxn", "tkz", "wj", "efo", "kei", "dau", "k", "axb", "n",
                "qa", "wit", "l", "ye", "jet", "a", "yxx", "bi", "n", "k", "a", "egk", "jtt", "w",
                "s", "sva", "gz", "tl", "o", "fsd", "kn", "xat", "pg", "f", "lti", "t", "z", "ef",
                "ojs", "zqb", "en", "ey", "qzb", "ll", "st", "f", "a", "v", "olr", "ak", "x", "b",
                "kkt", "yw", "cx", "u", "m", "mo", "w", "s", "ja", "wrp", "t", "g", "hel", "t",
                "vzi", "ig", "ou", "sa", "ys", "j", "pu", "gnq", "zjf", "b", "vs", "x", "las",
                "fma", "rj", "rwi", "o", "v", "a", "ia", "e", "gql", "kdq", "lk", "oc", "kh", "n",
                "b", "fko", "ed", "z", "o", "rfp", "jo", "nsx", "m", "df", "z", "ud", "tz", "w",
                "l", "yw", "n", "e", "odf", "kv", "rb", "m", "qs", "pih", "hbw", "f", "vw", "jlo",
                "n", "o", "iph", "j", "kyz", "tkn", "mxi", "en", "apm", "zzg", "sro", "uh", "x",
                "ngl", "kra", "cpz", "wo", "xr", "ggg", "fuf", "rbs", "y", "qjs", "e", "lh", "sa",
                "d", "m", "xt", "qcc", "wr", "rem", "gvg", "wnv", "nt", "j", "bo", "tzu", "bmv",
                "i", "dag", "pa", "pve", "p", "opu", "c", "fhq", "w", "eq", "o", "koe", "gbo", "sl",
                "lwx", "i", "jhh", "jw", "f", "kg", "r", "bq", "h", "cz", "x", "i", "x", "ttq",
                "tol", "r", "exp", "c", "e", "nzu", "yv", "hh", "hez", "bry", "eq", "knq", "dkt",
                "wcj", "ktw", "y", "iwe", "eq", "xf", "dmt", "ux", "nkn", "f", "t", "him", "p", "i",
                "u", "igm", "nms", "bqn", "x", "nng", "s", "a", "ylq", "z", "wy", "ni", "n", "ln",
                "de", "drk", "bng", "ai", "da", "f", "kij", "p", "i", "wb", "ylq", "br", "jg", "g",
                "dad", "v", "zef", "xo", "yl", "kwc", "tcr", "hkq", "dy", "hi", "dh", "a", "sy",
                "gkz", "qgo", "kjj", "z", "ewb", "le", "ph", "stb", "irm", "yfd", "yh", "gf", "z",
                "hp", "e", "q", "ns", "wnu", "us", "f", "t", "vjx", "kco", "yc", "niw", "d", "dql",
                "kvg", "xa", "e", "do", "qtl", "bz", "tto", "d", "dma", "gyv", "nh", "ea", "bi",
                "ix", "g", "dez", "tq", "b", "w", "da", "tea", "gk", "m", "uml", "fmh", "it", "elx",
                "x", "zoe", "kq", "rar", "esz", "quz", "i", "buc", "b", "fnj", "rgq", "n", "x", "c",
                "d", "qow", "c", "btt", "d", "fkk", "wqk", "o", "kjp", "vkq", "hbo", "g", "b",
                "yiy", "d", "pf", "bn", "s", "s", "w", "qzb", "ggk", "jyn", "czq", "a", "u", "p",
                "c", "mr", "mpl", "v", "k", "as", "xb", "isf", "r", "efp", "wn", "g", "orw", "gj",
                "i", "djv", "dg", "u", "fy", "ag", "h", "ce", "mf", "k", "hq", "ddh", "s", "ui",
                "m", "fv", "ne", "xa", "ovt", "ksc", "bo", "hp", "h", "aok", "tmo", "iux", "a", "f",
                "j", "is", "rj", "ych", "v", "ei", "lkg", "mdq", "th", "yj", "l", "od", "n", "ppm",
                "or", "o", "g", "gbm", "hm", "zvg", "sdn", "rqz", "haa", "m", "uq", "znv", "qzi",
                "xdx", "uju", "bp", "hl", "vy", "ujv", "f", "l", "r", "idw", "e", "fo", "h", "nb",
                "nb", "wp", "bw", "o", "qn", "ap", "p", "wl", "clj", "ob", "wqm", "fej", "ta", "t",
                "am", "n", "u", "to", "c", "azn", "yie", "b", "gj", "otr", "v", "y", "un", "xqb",
                "ygf", "rw", "a", "nt", "abv", "vsu", "gn", "pr", "l", "zt", "tnh", "uza", "ggs",
                "t", "s", "qp", "e", "y", "su", "vd", "wqz", "xmp", "l", "w", "rd", "ddm", "vvi",
                "s", "piq", "q", "z", "jp", "ree", "d", "jxa", "j", "bfe", "yy", "h", "zmt", "l",
                "yj", "hc", "i", "sm", "c", "zu", "um", "i", "rll", "pz", "pr", "bsb", "mc", "yj",
                "e", "vu", "pf", "bms", "qn", "xx", "mc", "h", "ej", "k", "gz", "f", "qtb", "xi",
                "zyl", "tpr", "h", "jo", "qz", "rye", "w", "q", "mru", "xd", "wfd", "ee", "z", "o",
                "e", "ja", "i", "uc", "zsr", "lt", "t", "y", "pn", "riz", "k", "m", "woz", "s",
                "kgd", "hdv", "b", "qg", "dn", "wjr", "v", "va", "cn", "s", "bkv", "ozf", "h",
                "ekb", "bp", "q", "ta", "yut", "sd", "nsa", "qip", "xzf", "z", "ht", "nd", "vc",
                "l", "e", "uq", "cd", "ap", "cml", "rtu", "t", "v", "n", "oay", "ng", "joj", "dqh",
                "dcr", "go", "fcw", "t", "kc", "uon", "nme", "qoo", "xnw", "anf", "uu", "mef",
                "ygr", "yzr", "nes", "s", "h", "l", "x", "ae", "f", "h", "hia", "fqi", "l", "von",
                "uoj", "r", "gqr", "drp", "n", "faa", "av", "ex", "wyl", "t", "dbq", "ek", "nke",
                "pvq", "gkl", "url", "z", "os", "s", "ga", "bo", "dhq", "z", "a", "g", "l", "tvo",
                "kr", "sgs", "cy", "o", "bg", "fge", "b", "p", "wry", "u", "jg", "dup", "sbt", "hq",
                "t", "ag", "rs", "c", "k", "fd", "c", "dr", "bra", "fmp", "g", "qwc", "w", "hy",
                "q", "xgr", "n", "oh", "loe", "tt", "aut", "tvh", "ve", "u", "nn", "ujh", "dx", "g",
                "hlf", "nb", "j", "y", "l", "f", "i", "yc", "pyr", "lap", "uc", "oi", "mzp", "g",
                "tvp", "d", "bn", "dqx", "ls", "qzv", "fsj", "g", "h", "y", "oat", "dl", "r", "tv",
                "r", "ac", "dh", "avz", "gd", "wo", "bt", "iph", "tav", "pnq", "lu", "mz", "y", "c",
                "i", "ftf", "g", "d", "cp", "nd", "w", "v", "i", "wl", "x", "lie", "nk", "hj",
                "moz", "r", "tgn", "t", "jdq", "pwg", "bg", "dk", "o", "kgj", "fb", "l", "sby", "z",
                "x", "rlf", "bsu", "ps", "jlv", "oi", "mzo", "ttb", "kk", "r", "mc", "fow", "p",
                "o"},
                "foa", "n"));
    }
}
